# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# --- mega2560 or uno ide 1.0
BOARD_TAG    = nano328
# BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyUSB0
AVRDUDE_ARD_BAUDRATE=115200
CXXFLAGS_STD = -std=c++14
CXXFLAGS = -Wall -Wextra -pedantic

include ./Arduino-Makefile/Arduino.mk
