# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# --- mega2560 or uno ide 1.0
BOARD_TAG = nano
BOARD_SUB = nano328
BOARD_TAG    = uno
VARIANT = standard
ARDUINO_LIBS = Wire
ARDUINO_PORT = /dev/ttyUSB0
AVRDUDE_ARD_BAUDRATE=115200
CXXFLAGS_STD = -std=c++14
# CXXFLAGS = -Wall -Wextra -pedantic

ARDMK_DIR = ./Arduino-Makefile

include ./Arduino-Makefile/Arduino.mk
